# Globals
default-lease-time 86400; # 1 día
max-lease-time 691200; # 8 días
option domain-name "joseantonio.test";
option domain-name-servers 10.0.0.2, 4.4.4.4;
authoritative;

# Subnet
subnet 192.168.57.0 netmask 255.255.255.0 {
  range 192.168.57.20 192.168.57.50;
  option routers 192.168.57.10;
  option subnet-mask 255.255.255.0;
  option broadcast-address 192.168.57.255;
}
